name: food_scanner_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  
  # Standard Icons
  cupertino_icons: ^1.0.6
  
  # Camera and Gallery
  image_picker: ^1.1.2
  
  # Google AI (Gemini)
  google_generative_ai: ^0.4.6
  
  # Markdown Formatter (This was missing!)
  flutter_markdown: ^0.7.7+1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - a.env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/IconKitchen-Output/android/play_store_512.png"# Path to your downloaded icon